
#BLS AND HIWI DATA DOWNLOADS


###*******************************************************************
###NOTES BOX

#BLS_CPI only pulling through 1986 and jumps to 1997 with one month (may be okay due to S download)
#BLS_CPI prints in a random order
#BLS_JOB_UPD_M works (have some series commented out, and need to check on the status of these)

###*******************************************************************


task :bls_cpi_upd_m => :environment do

	bls_cpi_m = {
		"PC@HON.M" => %Q|Series.load_from_bls("CUURA426SA0", "M")|,
		"PCFB@HON.M" => %Q|Series.load_from_bls("CUURA426SAF", "M")|,
		"PCFBFD@HON.M" => %Q|Series.load_from_bls("CUURA426SAF1", "M")|,
		"PCFBFDHM@HON.M" => %Q|Series.load_from_bls("CUURA426SAF11", "M")|,
		"PCFBFDAW@HON.M" => %Q|Series.load_from_bls("CUURA426SEFV", "M")|,
		"PCFBFDBV@HON.M" => %Q|Series.load_from_bls("CUURA426SAF116", "M")|,
		"PCHS@HON.M" => %Q|Series.load_from_bls("CUURA426SAH", "M")|,
		"PCHSSH@HON.M" => %Q|Series.load_from_bls("CUURA426SAH1", "M")|,
		"PCHSSHRT@HON.M" => %Q|Series.load_from_bls("CUURA426SEHA", "M")|,
		"PCHSSHOW@HON.M" => %Q|Series.load_from_bls("CUURA426SEHC", "M")|,
		"PCHSFU@HON.M" => %Q|Series.load_from_bls("CUURA426SAH2", "M")|,
		"PCHSFUEL@HON.M" => %Q|Series.load_from_bls("CUURA426SAH21", "M")|,
		"PCHSFUGS@HON.M" => %Q|Series.load_from_bls("CUURA426SEHF", "M")|,
		"PCHSFUGSE@HON.M" => %Q|Series.load_from_bls("CUURA426SEHF01", "M")|,
		"PCHSFUGSU@HON.M" => %Q|Series.load_from_bls("CUURA426SEHF02", "M")|,
		"PCHSHF@HON.M" => %Q|Series.load_from_bls("CUURA426SAH3", "M")|,
		"PCAP@HON.M" => %Q|Series.load_from_bls("CUURA426SAA", "M")|,
		"PCTR@HON.M" => %Q|Series.load_from_bls("CUURA426SAT", "M")|,
		"PCTRPR@HON.M" => %Q|Series.load_from_bls("CUURA426SAT1", "M")|,
		"PCTRMF@HON.M" => %Q|Series.load_from_bls("CUURA426SETB", "M")|,
		"PCTRGS@HON.M" => %Q|Series.load_from_bls("CUURA426SETB01", "M")|,
		"PCTRGSRG@HON.M" => %Q|Series.load_from_bls("CUURA426SS47014", "M")|,
		"PCTRGSPR@HON.M" => %Q|Series.load_from_bls("CUURA426SS47016", "M")|,
		"PCMD@HON.M" => %Q|Series.load_from_bls("CUURA426SAM", "M")|,
		"PCRE@HON.M" => %Q|Series.load_from_bls("CUURA426SAR", "M")|,
		"PCED@HON.M" => %Q|Series.load_from_bls("CUURA426SAE", "M")|,
		"PCOT@HON.M" => %Q|Series.load_from_bls("CUURA426SAG", "M")|,
		"PCCM@HON.M" => %Q|Series.load_from_bls("CUURA426SAC", "M")|,
		"PCCM_FD@HON.M" => %Q|Series.load_from_bls("CUURA426SACL1", "M")|,
		"PCCM_FB@HON.M" => %Q|Series.load_from_bls("CUURA426SACL11", "M")|,
		"PCCMND@HON.M" => %Q|Series.load_from_bls("CUURA426SAN", "M")|,
		"PCCMND_FD@HON.M" => %Q|Series.load_from_bls("CUURA426SANL1", "M")|,
		"PCCMND_FB@HON.M" => %Q|Series.load_from_bls("CUURA426SANL11", "M")|,
		"PCCMDR@HON.M" => %Q|Series.load_from_bls("CUURA426SAD", "M")|,
		"PCSV@HON.M" => %Q|Series.load_from_bls("CUURA426SAS", "M")|,
		"PCSV_MD@HON.M" => %Q|Series.load_from_bls("CUURA426SASL5", "M")|,
		"PCSV_RN@HON.M" => %Q|Series.load_from_bls("CUURA426SASL2RS", "M")|,
		"PC_MD@HON.M" => %Q|Series.load_from_bls("CUURA426SA0L5", "M")|,
		"PC_EN@HON.M" => %Q|Series.load_from_bls("CUURA426SA0LE", "M")|,
		"PC_FDEN@HON.M" => %Q|Series.load_from_bls("CUURA426SA0L1E", "M")|,
		"PC_SH@HON.M" => %Q|Series.load_from_bls("CUURA426SA0L2", "M")|,
		"PCEN@HON.M" => %Q|Series.load_from_bls("CUURA426SA0E", "M")|
	}
	
	p = Packager.new
	p.add_definitions bls_cpi_m
	p.write_definitions_to "/Volumes/UHEROwork/data/bls/update/bls_cpi_upd_m_NEW.xls"
	
end

task :bls_cpi_upd_s => :environment do
	bls_cpi_s = {
		"PC@HON.S" => %Q|Series.load_from_bls("CUUSA426SA0", "S")|,
		"PCFB@HON.S" => %Q|Series.load_from_bls("CUUSA426SAF", "S")|,
		"PCFBFD@HON.S" => %Q|Series.load_from_bls("CUUSA426SAF1", "S")|,
		"PCFBFDHM@HON.S" => %Q|Series.load_from_bls("CUUSA426SAF11", "S")|,
		"PCFBFDAW@HON.S" => %Q|Series.load_from_bls("CUUSA426SEFV", "S")|,
		"PCFBFDBV@HON.S" => %Q|Series.load_from_bls("CUUSA426SAF116", "S")|,
		"PCHS@HON.S" => %Q|Series.load_from_bls("CUUSA426SAH", "S")|,
		"PCHSSH@HON.S" => %Q|Series.load_from_bls("CUUSA426SAH1", "S")|,
		"PCHSSHRT@HON.S" => %Q|Series.load_from_bls("CUUSA426SEHA", "S")|,
		"PCHSSHOW@HON.S" => %Q|Series.load_from_bls("CUUSA426SEHC", "S")|,
		"PCHSFU@HON.S" => %Q|Series.load_from_bls("CUUSA426SAH2", "S")|,
		"PCHSFUEL@HON.S" => %Q|Series.load_from_bls("CUUSA426SAH21", "S")|,
		"PCHSFUGS@HON.S" => %Q|Series.load_from_bls("CUUSA426SEHF", "S")|,
		"PCHSFUGSE@HON.S" => %Q|Series.load_from_bls("CUUSA426SEHF01", "S")|,
		"PCHSFUGSU@HON.S" => %Q|Series.load_from_bls("CUUSA426SEHF02", "S")|,
		"PCHSHF@HON.S" => %Q|Series.load_from_bls("CUUSA426SAH3", "S")|,
		"PCAP@HON.S" => %Q|Series.load_from_bls("CUUSA426SAA", "S")|,
		"PCTR@HON.S" => %Q|Series.load_from_bls("CUUSA426SAT", "S")|,
		"PCTRPR@HON.S" => %Q|Series.load_from_bls("CUUSA426SAT1", "S")|,
		"PCTRMF@HON.S" => %Q|Series.load_from_bls("CUUSA426SETB", "S")|,
		"PCTRGS@HON.S" => %Q|Series.load_from_bls("CUUSA426SETB01", "S")|,
		"PCTRGSRG@HON.S" => %Q|Series.load_from_bls("CUUSA426SS47014", "S")|,
		"PCTRGSMD@HON.S" => %Q|Series.load_from_bls("CUUSA426SS47015", "S")|,
		"PCTRGSPR@HON.S" => %Q|Series.load_from_bls("CUUSA426SS47016", "S")|,
		"PCMD@HON.S" => %Q|Series.load_from_bls("CUUSA426SAM", "S")|,
		"PCRE@HON.S" => %Q|Series.load_from_bls("CUUSA426SAR", "S")|,
		"PCED@HON.S" => %Q|Series.load_from_bls("CUUSA426SAE", "S")|,
		"PCOT@HON.S" => %Q|Series.load_from_bls("CUUSA426SAG", "S")|,
		"PCCM@HON.S" => %Q|Series.load_from_bls("CUUSA426SAC", "S")|,
		"PCCM_FD@HON.S" => %Q|Series.load_from_bls("CUUSA426SACL1", "S")|,
		"PCCM_FB@HON.S" => %Q|Series.load_from_bls("CUUSA426SACL11", "S")|,
		"PCCMND@HON.S" => %Q|Series.load_from_bls("CUUSA426SAN", "S")|,
		"PCCMND_FD@HON.S" => %Q|Series.load_from_bls("CUUSA426SANL1", "S")|,
		"PCCMND_FB@HON.S" => %Q|Series.load_from_bls("CUUSA426SANL11", "S")|,
		"PCCMDR@HON.S" => %Q|Series.load_from_bls("CUUSA426SAD", "S")|,
		"PCSV@HON.S" => %Q|Series.load_from_bls("CUUSA426SAS", "S")|,
		"PCSV_MD@HON.S" => %Q|Series.load_from_bls("CUUSA426SASL5", "S")|,
		"PCSV_RN@HON.S" => %Q|Series.load_from_bls("CUUSA426SASL2RS", "S")|,
		"PC_MD@HON.S" => %Q|Series.load_from_bls("CUUSA426SA0L5", "S")|,
		"PC_EN@HON.S" => %Q|Series.load_from_bls("CUUSA426SA0LE", "S")|,
		"PC_FDEN@HON.S" => %Q|Series.load_from_bls("CUUSA426SA0L1E", "S")|,
		"PC_SH@HON.S" => %Q|Series.load_from_bls("CUUSA426SA0L2", "S")|,
		"PCEN@HON.S" => %Q|Series.load_from_bls("CUUSA426SA0E", "S")|
	}
	
	p = Packager.new
	p.add_definitions bls_cpi_s
	p.write_definitions_to "/Volumes/UHEROwork/data/bls/update/bls_cpi_upd_s_NEW.xls"
	
end

task :bls_job_upd_m => :environment do

	bls_job_m = {
    "E_NFSA@HI.M" => %Q|Series.load_from_bls("SMS15000000000000001", "M")|,
    "ECTSA@HI.M" => %Q|Series.load_from_bls("SMS15000001500000001", "M")|,
#   "EMNSA@HI.M" => %Q|Series.load_from_bls("SMS15000003000000001", "M")|,
    "E_TTUSA@HI.M" => %Q|Series.load_from_bls("SMS15000004000000001", "M")|,
    "E_EDHCSA@HI.M" => %Q|Series.load_from_bls("SMS15000006500000001", "M")|,
    "E_LHSA@HI.M" => %Q|Series.load_from_bls("SMS15000007000000001", "M")|,
    "EOSSA@HI.M" => %Q|Series.load_from_bls("SMS15000008000000001", "M")|,
    "EGVSA@HI.M" => %Q|Series.load_from_bls("SMS15000009000000001", "M")|,
    "EWTSA@HI.M" => %Q|Series.load_from_bls("SMS15000004100000001", "M")|,
    "ERTSA@HI.M" => %Q|Series.load_from_bls("SMS15000004200000001", "M")|,
    "E_FIRSA@HI.M" => %Q|Series.load_from_bls("SMS15000005500000001", "M")|,
    "ERESA@HI.M" => %Q|Series.load_from_bls("SMS15000005553000001", "M")|,
    "E_PBSSA@HI.M" => %Q|Series.load_from_bls("SMS15000006000000001", "M")|,
    "EPSSA@HI.M" => %Q|Series.load_from_bls("SMS15000006054000001", "M")|,
    "EEDSA@HI.M" => %Q|Series.load_from_bls("SMS15000006561000001", "M")|,
    "EHCSA@HI.M" => %Q|Series.load_from_bls("SMS15000006562000001", "M")|,
    "EAESA@HI.M" => %Q|Series.load_from_bls("SMS15000007071000001", "M")|,
    "EAFSA@HI.M" => %Q|Series.load_from_bls("SMS15000007072000001", "M")|,
    "EGVFDSA@HI.M" => %Q|Series.load_from_bls("SMS15000009091000001", "M")|,
    "EGVSTSA@HI.M" => %Q|Series.load_from_bls("SMS15000009092000001", "M")|,
    "EGVLCSA@HI.M" => %Q|Series.load_from_bls("SMS15000009093000001", "M")|,
    "EMPLSA@HI.M" => %Q|Series.load_from_bls("LASST15000005", "M")|,
    "EMPLNS@HI.M" => %Q|Series.load_from_bls("LAUST15000005", "M")|,
    "EMPLNS@HON.M" => %Q|Series.load_from_bls("LAUPS15007005", "M")|,
    "EMPLNS@HAW.M" => %Q|Series.load_from_bls("LAUPA15010005", "M")|,
    "EMPLNS@MAU.M" => %Q|Series.load_from_bls("LAUPA15015005", "M")|,
    "EMPLNS@KAU.M" => %Q|Series.load_from_bls("LAUCN15007005", "M")|,
#   "LFSA@HI.M" => %Q|Series.load_from_bls("LASST15000006 ", "M")|,
    "LFNS@HI.M" => %Q|Series.load_from_bls("LAUST15000006", "M")|,
    "LFNS@HON.M" => %Q|Series.load_from_bls("LAUPS15007006", "M")|,
    "LFNS@HAW.M" => %Q|Series.load_from_bls("LAUPA15010006", "M")|,
    "LFNS@MAU.M" => %Q|Series.load_from_bls("LAUPA15015006", "M")|,
    "LFNS@KAU.M" => %Q|Series.load_from_bls("LAUCN15007006", "M")|,
#   "URSA@HI.M" => %Q|Series.load_from_bls("LASST15000003 ", "M")|,
    "URNS@HI.M" => %Q|Series.load_from_bls("LAUST15000003", "M")|,
    "URNS@HON.M" => %Q|Series.load_from_bls("LAUPS15007003", "M")|,
    "URNS@HAW.M" => %Q|Series.load_from_bls("LAUPA15010003", "M")|,
    "URNS@MAU.M" => %Q|Series.load_from_bls("LAUPA15015003", "M")|,
    "URNS@KAU.M" => %Q|Series.load_from_bls("LAUCN15007003", "M")|,
    "WWCTNS@HI.M" => %Q|Series.load_from_bls("SMU15000001500000030", "M")|,
    "WHCTNS@HI.M" => %Q|Series.load_from_bls("SMU15000001500000008", "M")|,
    "WWMNNS@HI.M" => %Q|Series.load_from_bls("SMU15000003000000030", "M")|,
    "WHMNNS@HI.M" => %Q|Series.load_from_bls("SMU15000003000000008", "M")|,
    "WW_TTUNS@HI.M" => %Q|Series.load_from_bls("SMU15000004000000030", "M")|,
    "WH_TTUNS@HI.M" => %Q|Series.load_from_bls("SMU15000004000000008", "M")|,
    "WWWTNS@HI.M" => %Q|Series.load_from_bls("SMU15000004100000030", "M")|,
    "WHWTNS@HI.M" => %Q|Series.load_from_bls("SMU15000004100000008", "M")|,
    "WWRTNS@HI.M" => %Q|Series.load_from_bls("SMU15000004200000030", "M")|,
    "WHRTNS@HI.M" => %Q|Series.load_from_bls("SMU15000004200000008", "M")|,
#   "WWIFNS@HI.M" => %Q|Series.load_from_bls("SMU15000005000000030", "M")|,
#   "WHIFNS@HI.M" => %Q|Series.load_from_bls("SMU15000005000000008", "M")|,
    "WW_FINNS@HI.M" => %Q|Series.load_from_bls("SMU15000005500000030", "M")|,
    "WH_FINNS@HI.M" => %Q|Series.load_from_bls("SMU15000005500000008", "M")|,
    "WWAFNS@HI.M" => %Q|Series.load_from_bls("SMU15000007072000030", "M")|,
    "WHAFNS@HI.M" => %Q|Series.load_from_bls("SMU15000007072000008", "M")|,
     "WWAFACNS@HI.M" => %Q|Series.load_from_bls("SMU15000007072100030", "M")|,
     "WHAFACNS@HI.M" => %Q|Series.load_from_bls("SMU15000007072100008", "M")|,
#   "WWAFFDNS@HI.M" => %Q|Series.load_from_bls("SMU15000007072200030", "M")|,
#   "WHAFFDNS@HI.M" => %Q|Series.load_from_bls("SMU15000007072200008", "M")|,
    "WWCTNS@HON.M" => %Q|Series.load_from_bls("SMU15261801500000030", "M")|,
    "WHCTNS@HON.M" => %Q|Series.load_from_bls("SMU15261801500000008", "M")|,
    "WWMNNS@HON.M" => %Q|Series.load_from_bls("SMU15261803000000030", "M")|,
    "WHMNNS@HON.M" => %Q|Series.load_from_bls("SMU15261803000000008", "M")|,
    "WW_TTUNS@HON.M" => %Q|Series.load_from_bls("SMU15261804000000030", "M")|,
    "WH_TTUNS@HON.M" => %Q|Series.load_from_bls("SMU15261804000000008", "M")|,
    "WWWTNS@HON.M" => %Q|Series.load_from_bls("SMU15261804100000030", "M")|,
    "WHWTNS@HON.M" => %Q|Series.load_from_bls("SMU15261804100000008", "M")|,
    "WWRTNS@HON.M" => %Q|Series.load_from_bls("SMU15261804200000030", "M")|,
    "WHRTNS@HON.M" => %Q|Series.load_from_bls("SMU15261804200000008", "M")|,
#   "WWIFNS@HON.M" => %Q|Series.load_from_bls("SMU15261805000000030", "M")|,
#   "WHIFNS@HON.M" => %Q|Series.load_from_bls("SMU15261805000000008", "M")|,
    "WW_FINNS@HON.M" => %Q|Series.load_from_bls("SMU15261805500000030", "M")|,
    "WH_FINNS@HON.M" => %Q|Series.load_from_bls("SMU15261805500000008", "M")|,
    "WWAFNS@HON.M" => %Q|Series.load_from_bls("SMU15261807072000030", "M")|,
    "WHAFNS@HON.M" => %Q|Series.load_from_bls("SMU15261807072000008", "M")|,
#   "WWAFACNS@HON.M" => %Q|Series.load_from_bls("SMU15261807072100030", "M")|,
#   "WHAFACNS@HON.M" => %Q|Series.load_from_bls("SMU15261807072100008", "M")|,
    "WWAFFDNS@HON.M" => %Q|Series.load_from_bls("SMU15261807072200030", "M")|,
    "WHAFFDNS@HON.M" => %Q|Series.load_from_bls("SMU15261807072200008", "M")|,
    "E_NFNS@HI.M" => %Q|Series.load_from_bls("SMU15000000000000001", "M")|,
    "E_PRNS@HI.M" => %Q|Series.load_from_bls("SMU15000000500000001", "M")|,
    "E_GDSPRNS@HI.M" => %Q|Series.load_from_bls("SMU15000000600000001", "M")|,
    "E_SVCPRNS@HI.M" => %Q|Series.load_from_bls("SMU15000000700000001", "M")|,
    "E_PRSVCPRNS@HI.M" => %Q|Series.load_from_bls("SMU15000000800000001", "M")|,
    "ECTNS@HI.M" => %Q|Series.load_from_bls("SMU15000001500000001", "M")|,
    "ECTBLNS@HI.M" => %Q|Series.load_from_bls("SMU15000001523600001", "M")|,
    "ECTSPNS@HI.M" => %Q|Series.load_from_bls("SMU15000001523800001", "M")|,
    "EMNNS@HI.M" => %Q|Series.load_from_bls("SMU15000003000000001", "M")|,
    "EMNDRNS@HI.M" => %Q|Series.load_from_bls("SMU15000003100000001", "M")|,
    "EMNNDNS@HI.M" => %Q|Series.load_from_bls("SMU15000003200000001", "M")|,
    "E_TTUNS@HI.M" => %Q|Series.load_from_bls("SMU15000004000000001", "M")|,
    "EWTNS@HI.M" => %Q|Series.load_from_bls("SMU15000004100000001", "M")|,
    "ERTNS@HI.M" => %Q|Series.load_from_bls("SMU15000004200000001", "M")|,
    "ERTFDNS@HI.M" => %Q|Series.load_from_bls("SMU15000004244500001", "M")|,
    "ERTFDGSNS@HI.M" => %Q|Series.load_from_bls("SMU15000004244510001", "M")|,
    "ERTCLNS@HI.M" => %Q|Series.load_from_bls("SMU15000004244800001", "M")|,
    "ERTGMNS@HI.M" => %Q|Series.load_from_bls("SMU15000004245200001", "M")|,
    "ERTGMDSNS@HI.M" => %Q|Series.load_from_bls("SMU15000004245210001", "M")|,
    "E_TUNS@HI.M" => %Q|Series.load_from_bls("SMU15000004300000001", "M")|,
    "EUTNS@HI.M" => %Q|Series.load_from_bls("SMU15000004322000001", "M")|,
    "ETWNS@HI.M" => %Q|Series.load_from_bls("SMU15000004340008901", "M")|,
    "ETWTANS@HI.M" => %Q|Series.load_from_bls("SMU15000004348100001", "M")|,
    "EIFNS@HI.M" => %Q|Series.load_from_bls("SMU15000005000000001", "M")|,
    "EIFTCNS@HI.M" => %Q|Series.load_from_bls("SMU15000005051700001", "M")|,
    "E_FIRNS@HI.M" => %Q|Series.load_from_bls("SMU15000005500000001", "M")|,
    "EFINS@HI.M" => %Q|Series.load_from_bls("SMU15000005552000001", "M")|,
    "ERENS@HI.M" => %Q|Series.load_from_bls("SMU15000005553000001", "M")|,
    "E_PBSNS@HI.M" => %Q|Series.load_from_bls("SMU15000006000000001", "M")|,
    "EPSNS@HI.M" => %Q|Series.load_from_bls("SMU15000006054000001", "M")|,
    "EMANS@HI.M" => %Q|Series.load_from_bls("SMU15000006055000001", "M")|,
    "EADNS@HI.M" => %Q|Series.load_from_bls("SMU15000006056000001", "M")|,
    "EADESNS@HI.M" => %Q|Series.load_from_bls("SMU15000006056130001", "M")|,
    "E_EDHCNS@HI.M" => %Q|Series.load_from_bls("SMU15000006500000001", "M")|,
    "EEDNS@HI.M" => %Q|Series.load_from_bls("SMU15000006561000001", "M")|,
    "EED12NS@HI.M" => %Q|Series.load_from_bls("SMU15000006561110001", "M")|,
    "EHCNS@HI.M" => %Q|Series.load_from_bls("SMU15000006562000001", "M")|,
    "EHCAMNS@HI.M" => %Q|Series.load_from_bls("SMU15000006562100001", "M")|,
    "EHCHONS@HI.M" => %Q|Series.load_from_bls("SMU15000006562200001", "M")|,
    "EHCNRNS@HI.M" => %Q|Series.load_from_bls("SMU15000006562300001", "M")|,
    "EHCSONS@HI.M" => %Q|Series.load_from_bls("SMU15000006562400001", "M")|,
    "EHCSOIFNS@HI.M" => %Q|Series.load_from_bls("SMU15000006562410001", "M")|,
    "E_LHNS@HI.M" => %Q|Series.load_from_bls("SMU15000007000000001", "M")|,
    "EAENS@HI.M" => %Q|Series.load_from_bls("SMU15000007071000001", "M")|,
    "EAFNS@HI.M" => %Q|Series.load_from_bls("SMU15000007072000001", "M")|,
    "EAFACNS@HI.M" => %Q|Series.load_from_bls("SMU15000007072100001", "M")|,
    "EAFFDNS@HI.M" => %Q|Series.load_from_bls("SMU15000007072200001", "M")|,
    "EAFFDRSNS@HI.M" => %Q|Series.load_from_bls("SMU15000007072210001", "M")|,
    "EOSNS@HI.M" => %Q|Series.load_from_bls("SMU15000008000000001", "M")|,
    "EGVNS@HI.M" => %Q|Series.load_from_bls("SMU15000009000000001", "M")|,
    "EGVFDNS@HI.M" => %Q|Series.load_from_bls("SMU15000009091000001", "M")|,
    "EGVFDSPNS@HI.M" => %Q|Series.load_from_bls("SMU15000009091336601", "M")|,
#   "EGVFDDDNS@HI.M" => %Q|Series.load_from_bls("SMU15000009091911001", "M")|,
    "EGVSTNS@HI.M" => %Q|Series.load_from_bls("SMU15000009092000001", "M")|,
    "EGVSTEDNS@HI.M" => %Q|Series.load_from_bls("SMU15000009092161101", "M")|,
    "EGVLCNS@HI.M" => %Q|Series.load_from_bls("SMU15000009093000001", "M")|,
    "E_NFNS@HON.M" => %Q|Series.load_from_bls("SMU15261800000000001", "M")|,
    "E_PRNS@HON.M" => %Q|Series.load_from_bls("SMU15261800500000001", "M")|,
    "E_GDSPRNS@HON.M" => %Q|Series.load_from_bls("SMU15261800600000001", "M")|,
    "E_SVCPRNS@HON.M" => %Q|Series.load_from_bls("SMU15261800700000001", "M")|,
    "E_PRSVCPRNS@HON.M" => %Q|Series.load_from_bls("SMU15261800800000001", "M")|,
    "ECTNS@HON.M" => %Q|Series.load_from_bls("SMU15261801500000001", "M")|,
    "ECTSPNS@HON.M" => %Q|Series.load_from_bls("SMU15261801523800001", "M")|,
    "EMNNS@HON.M" => %Q|Series.load_from_bls("SMU15261803000000001", "M")|,
    "EMNDRNS@HON.M" => %Q|Series.load_from_bls("SMU15261803100000001", "M")|,
    "EMNNDNS@HON.M" => %Q|Series.load_from_bls("SMU15261803200000001", "M")|,
    "E_TTUNS@HON.M" => %Q|Series.load_from_bls("SMU15261804000000001", "M")|,
    "EWTNS@HON.M" => %Q|Series.load_from_bls("SMU15261804100000001", "M")|,
    "ERTNS@HON.M" => %Q|Series.load_from_bls("SMU15261804200000001", "M")|,
    "ERTFDNS@HON.M" => %Q|Series.load_from_bls("SMU15261804244500001", "M")|,
    "ERTFDGSNS@HON.M" => %Q|Series.load_from_bls("SMU15261804244510001", "M")|,
    "ERTCLNS@HON.M" => %Q|Series.load_from_bls("SMU15261804244800001", "M")|,
    "ERTGMNS@HON.M" => %Q|Series.load_from_bls("SMU15261804245200001", "M")|,
    "ERTGMDSNS@HON.M" => %Q|Series.load_from_bls("SMU15261804245210001", "M")|,
    "E_TUNS@HON.M" => %Q|Series.load_from_bls("SMU15261804300000001", "M")|,
    "ETWNS@HON.M" => %Q|Series.load_from_bls("SMU15261804340008901", "M")|,
    "ETWTANS@HON.M" => %Q|Series.load_from_bls("SMU15261804348100001", "M")|,
    "EIFNS@HON.M" => %Q|Series.load_from_bls("SMU15261805000000001", "M")|,
    "EIFTCNS@HON.M" => %Q|Series.load_from_bls("SMU15261805051700001", "M")|,
    "E_FIRNS@HON.M" => %Q|Series.load_from_bls("SMU15261805500000001", "M")|,
    "EFINS@HON.M" => %Q|Series.load_from_bls("SMU15261805552000001", "M")|,
    "ERENS@HON.M" => %Q|Series.load_from_bls("SMU15261805553000001", "M")|,
    "E_PBSNS@HON.M" => %Q|Series.load_from_bls("SMU15261806000000001", "M")|,
    "EPSNS@HON.M" => %Q|Series.load_from_bls("SMU15261806054000001", "M")|,
    "EMANS@HON.M" => %Q|Series.load_from_bls("SMU15261806055000001", "M")|,
    "EADNS@HON.M" => %Q|Series.load_from_bls("SMU15261806056000001", "M")|,
    "EADESNS@HON.M" => %Q|Series.load_from_bls("SMU15261806056130001", "M")|,
    "E_EDHCNS@HON.M" => %Q|Series.load_from_bls("SMU15261806500000001", "M")|,
    "EEDNS@HON.M" => %Q|Series.load_from_bls("SMU15261806561000001", "M")|,
    "EED12NS@HON.M" => %Q|Series.load_from_bls("SMU15261806561110001", "M")|,
    "EHCNS@HON.M" => %Q|Series.load_from_bls("SMU15261806562000001", "M")|,
    "EHCAMNS@HON.M" => %Q|Series.load_from_bls("SMU15261806562100001", "M")|,
    "EHCHONS@HON.M" => %Q|Series.load_from_bls("SMU15261806562200001", "M")|,
    "E_LHNS@HON.M" => %Q|Series.load_from_bls("SMU15261807000000001", "M")|,
    "EAFNS@HON.M" => %Q|Series.load_from_bls("SMU15261807072000001", "M")|,
    "EAFACNS@HON.M" => %Q|Series.load_from_bls("SMU15261807072100001", "M")|,
    "EAFFDNS@HON.M" => %Q|Series.load_from_bls("SMU15261807072200001", "M")|,
    "EAFFDRSNS@HON.M" => %Q|Series.load_from_bls("SMU15261807072210001", "M")|,
    "EOSNS@HON.M" => %Q|Series.load_from_bls("SMU15261808000000001", "M")|,
    "EGVNS@HON.M" => %Q|Series.load_from_bls("SMU15261809000000001", "M")|,
    "EGVFDNS@HON.M" => %Q|Series.load_from_bls("SMU15261809091000001", "M")|,
    "EGVFDSPNS@HON.M" => %Q|Series.load_from_bls("SMU15261809091336601", "M")|,
#   "EGVFDDDNS@HON.M" => %Q|Series.load_from_bls("SMU15261809091911001", "M")|,
		"EGVSTNS@HON.M" => %Q|Series.load_from_bls("SMU15261809092000001", "M")|,
		"EGVSTEDNS@HON.M" => %Q|Series.load_from_bls("SMU15261809092161101", "M")|,
		"EGVLCNS@HON.M" => %Q|Series.load_from_bls("SMU15261809093000001", "M")|
	}
	
	p = Packager.new
	p.add_definitions bls_job_m
	p.write_definitions_to "/Volumes/UHEROwork/data/bls/update/bls_job_upd_m_NEW.xls"
	
end



task :hiwi_upd => :environment do
  hiwi_upd = {
    'E_NFNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:WAGE & SALARY JOBS", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_PRNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Total Private", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_GDSPRNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Goods-Producing", :col => "repeat:3:14" , :frequency => "M"}|,
    'ECTNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Nat. Resources & Mining & Construction", :col => "repeat:3:14" , :frequency => "M"}|,
    'ECTBLNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Construction of Buildings", :col => "repeat:3:14" , :frequency => "M"}|,
    'ECTSPNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Special Trade Contractors", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMNNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Manufacturing", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMNDRNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Durable Goods", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMNNDNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Non-Durable Goods", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_SVCPRNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Service-Providing", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_PRSVCPRNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Private Service-Providing", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_TTUNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Trade, Transportation & Utilities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EWTNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Wholesale Trade", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Retail Trade", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTFDNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Food & Beverage Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTFDGSNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Grocery Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTCLNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Clothing & Clothing Accessories Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTGMNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:General Merchandise", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTGMDSNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Department Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_TUNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Transportation, Warehousing & Utilities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EUTNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Utilites", :col => "repeat:3:14" , :frequency => "M"}|,
    'ETWNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Transportation & Warehousing", :col => "repeat:3:14" , :frequency => "M"}|,
    'ETWTANS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Air Transportation", :col => "repeat:3:14" , :frequency => "M"}|,
    'EIFNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Information", :col => "repeat:3:14" , :frequency => "M"}|,
    'EIFTCNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Telecommunications", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_FIRNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Financial Activities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EFINS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Finance & Insurance", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERENS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Real Estate & Rental & Leasing", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_PBSNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Professional & Business Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EPSNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Professional, Scientific & Tech. Svcs.", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMANS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Management of Companies & Enterprises", :col => "repeat:3:14" , :frequency => "M"}|,
    'EADNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Management & Remediation Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EADESNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Employment Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_EDHCNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Educational & Health Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EEDNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Educational Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EED12NS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Elementary & Secondary Schools", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Health Care & Social Assistance", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCAMNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Ambulatory Health Care Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCHONS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Hospitals", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCNRNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Nursing & Residenial Care Facilities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCSONS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Social Assistance", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCSOIFNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Individual & Family Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_LHNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Leisure and Hospitality", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAENS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Arts, Entertainment, & Recreation", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Accommodation & Food Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFACNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Accommodation", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFFDNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Food Services & Drinking Places", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFFDRSNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Full-Service Restaurants", :col => "repeat:3:14" , :frequency => "M"}|,
    'EOSNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Other Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVFDNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Federal Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVFDDDNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Department of Defense", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVFDSPNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Naval Shipyard", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVSTNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:State Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVSTEDNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:State Education", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVLCNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:Local Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAGNS@HI.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "State", :row => "header:col:1:AGRICULTURE", :col => "repeat:3:14" , :frequency => "M"}|,
  
    'E_NFNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:WAGE & SALARY JOBS", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_PRNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Total Private", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_GDSPRNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Goods-Producing", :col => "repeat:3:14" , :frequency => "M"}|,
    'ECTNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Nat. Resources & Mining & Construction", :col => "repeat:3:14" , :frequency => "M"}|,
    'ECTBLNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Construction of Buildings", :col => "repeat:3:14" , :frequency => "M"}|,
    'ECTSPNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Special Trade Contractors", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMNNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Manufacturing", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMNDRNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Durable Goods", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMNNDNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Non-Durable Goods", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_SVCPRNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Service-Providing", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_PRSVCPRNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Private Service-Providing", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_TTUNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Trade, Transportation & Utilities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EWTNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Wholesale Trade", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Retail Trade", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTFDNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Food & Beverage Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTFDGSNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Grocery Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTCLNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Clothing & Clothing Accessories Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTGMNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:General Merchandise", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTGMDSNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Department Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_TUNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Transportation, Warehousing & Utilities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EUTNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Utilites", :col => "repeat:3:14" , :frequency => "M"}|,
    'ETWNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Transportation & Warehousing", :col => "repeat:3:14" , :frequency => "M"}|,
    'ETWTANS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Air Transportation", :col => "repeat:3:14" , :frequency => "M"}|,
    'EIFNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Information", :col => "repeat:3:14" , :frequency => "M"}|,
    'EIFTCNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Telecommunications", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_FIRNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Financial Activities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EFINS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Finance & Insurance", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERENS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Real Estate & Rental & Leasing", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_PBSNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Professional & Business Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EPSNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Professional, Scientific & Tech. Svcs.", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMANS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Management of Companies & Enterprises", :col => "repeat:3:14" , :frequency => "M"}|,
    'EADNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Management & Remediation Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EADESNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Employment Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_EDHCNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Educational & Health Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EEDNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Educational Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EED12NS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Elementary & Secondary Schools", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Health Care & Social Assistance", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCAMNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Ambulatory Health Care Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCHONS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Hospitals", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCNRNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Nursing & Residenial Care Facilities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCSONS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Social Assistance", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCSOIFNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Individual & Family Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_LHNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Leisure and Hospitality", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAENS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Arts, Entertainment, & Recreation", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Accommodation & Food Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFACNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Accommodation", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFFDNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Food Services & Drinking Places", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFFDRSNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Full-Service Restaurants", :col => "repeat:3:14" , :frequency => "M"}|,
    'EOSNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Other Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVFDNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Federal Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVFDDDNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Department of Defense", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVFDSPNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Naval Shipyard", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVSTNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:State Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVSTEDNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:State Education", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVLCNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:Local Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAGNS@HON.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "Oahu", :row => "header:col:1:AGRICULTURE", :col => "repeat:3:14" , :frequency => "M"}|,


    'E_NFNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:WAGE & SALARY JOBS", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_PRNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Total Private", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_GDSPRNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Goods-Producing", :col => "repeat:3:14" , :frequency => "M"}|,
    'ECTNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Nat. Resources & Mining & Construction", :col => "repeat:3:14" , :frequency => "M"}|,
    'ECTBLNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Construction of Buildings", :col => "repeat:3:14" , :frequency => "M"}|,
    'ECTSPNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Special Trade Contractors", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMNNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Manufacturing", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMNDRNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Durable Goods", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMNNDNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Non-Durable Goods", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_SVCPRNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Service-Providing", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_PRSVCPRNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Private Service-Providing", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_TTUNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Trade, Transportation & Utilities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EWTNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Wholesale Trade", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Retail Trade", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTFDNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Food & Beverage Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTFDGSNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Grocery Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTCLNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Clothing & Clothing Accessories Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTGMNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:General Merchandise", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTGMDSNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Department Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_TUNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Transportation, Warehousing & Utilities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EUTNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Utilites", :col => "repeat:3:14" , :frequency => "M"}|,
    'ETWNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Transportation & Warehousing", :col => "repeat:3:14" , :frequency => "M"}|,
    'ETWTANS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Air Transportation", :col => "repeat:3:14" , :frequency => "M"}|,
    'EIFNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Information", :col => "repeat:3:14" , :frequency => "M"}|,
    'EIFTCNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Telecommunications", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_FIRNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Financial Activities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EFINS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Finance & Insurance", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERENS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Real Estate & Rental & Leasing", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_PBSNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Professional & Business Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EPSNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Professional, Scientific & Tech. Svcs.", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMANS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Management of Companies & Enterprises", :col => "repeat:3:14" , :frequency => "M"}|,
    'EADNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Management & Remediation Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EADESNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Employment Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_EDHCNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Educational & Health Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EEDNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Educational Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EED12NS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Elementary & Secondary Schools", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Health Care & Social Assistance", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCAMNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Ambulatory Health Care Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCHONS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Hospitals", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCNRNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Nursing & Residenial Care Facilities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCSONS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Social Assistance", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCSOIFNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Individual & Family Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_LHNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Leisure and Hospitality", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAENS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Arts, Entertainment, & Recreation", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Accommodation & Food Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFACNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Accommodation", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFFDNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Food Services & Drinking Places", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFFDRSNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Full-Service Restaurants", :col => "repeat:3:14" , :frequency => "M"}|,
    'EOSNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Other Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVFDNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Federal Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVFDDDNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Department of Defense", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVFDSPNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Naval Shipyard", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVSTNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:State Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVSTEDNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:State Education", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVLCNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:Local Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAGNS@HAW.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "HCty", :row => "header:col:1:AGRICULTURE", :col => "repeat:3:14" , :frequency => "M"}|,


    'E_NFNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:WAGE & SALARY JOBS", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_PRNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Total Private", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_GDSPRNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Goods-Producing", :col => "repeat:3:14" , :frequency => "M"}|,
    'ECTNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Nat. Resources & Mining & Construction", :col => "repeat:3:14" , :frequency => "M"}|,
    'ECTBLNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Construction of Buildings", :col => "repeat:3:14" , :frequency => "M"}|,
    'ECTSPNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Special Trade Contractors", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMNNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Manufacturing", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMNDRNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Durable Goods", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMNNDNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Non-Durable Goods", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_SVCPRNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Service-Providing", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_PRSVCPRNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Private Service-Providing", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_TTUNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Trade, Transportation & Utilities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EWTNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Wholesale Trade", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Retail Trade", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTFDNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Food & Beverage Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTFDGSNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Grocery Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTCLNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Clothing & Clothing Accessories Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTGMNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:General Merchandise", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTGMDSNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Department Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_TUNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Transportation, Warehousing & Utilities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EUTNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Utilites", :col => "repeat:3:14" , :frequency => "M"}|,
    'ETWNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Transportation & Warehousing", :col => "repeat:3:14" , :frequency => "M"}|,
    'ETWTANS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Air Transportation", :col => "repeat:3:14" , :frequency => "M"}|,
    'EIFNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Information", :col => "repeat:3:14" , :frequency => "M"}|,
    'EIFTCNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Telecommunications", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_FIRNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Financial Activities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EFINS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Finance & Insurance", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERENS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Real Estate & Rental & Leasing", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_PBSNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Professional & Business Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EPSNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Professional, Scientific & Tech. Svcs.", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMANS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Management of Companies & Enterprises", :col => "repeat:3:14" , :frequency => "M"}|,
    'EADNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Management & Remediation Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EADESNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Employment Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_EDHCNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Educational & Health Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EEDNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Educational Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EED12NS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Elementary & Secondary Schools", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Health Care & Social Assistance", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCAMNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Ambulatory Health Care Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCHONS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Hospitals", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCNRNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Nursing & Residenial Care Facilities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCSONS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Social Assistance", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCSOIFNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Individual & Family Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_LHNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Leisure and Hospitality", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAENS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Arts, Entertainment, & Recreation", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Accommodation & Food Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFACNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Accommodation", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFFDNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Food Services & Drinking Places", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFFDRSNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Full-Service Restaurants", :col => "repeat:3:14" , :frequency => "M"}|,
    'EOSNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Other Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVFDNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Federal Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVFDDDNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Department of Defense", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVFDSPNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Naval Shipyard", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVSTNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:State Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVSTEDNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:State Education", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVLCNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:Local Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAGNS@KAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "KCty", :row => "header:col:1:AGRICULTURE", :col => "repeat:3:14" , :frequency => "M"}|,

    'E_NFNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:WAGE & SALARY JOBS", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_PRNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Total Private", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_GDSPRNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Goods-Producing", :col => "repeat:3:14" , :frequency => "M"}|,
    'ECTNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Nat. Resources & Mining & Construction", :col => "repeat:3:14" , :frequency => "M"}|,
    'ECTBLNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Construction of Buildings", :col => "repeat:3:14" , :frequency => "M"}|,
    'ECTSPNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Special Trade Contractors", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMNNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Manufacturing", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMNDRNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Durable Goods", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMNNDNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Non-Durable Goods", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_SVCPRNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Service-Providing", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_PRSVCPRNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Private Service-Providing", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_TTUNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Trade, Transportation & Utilities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EWTNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Wholesale Trade", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Retail Trade", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTFDNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Food & Beverage Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTFDGSNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Grocery Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTCLNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Clothing & Clothing Accessories Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTGMNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:General Merchandise", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERTGMDSNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Department Stores", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_TUNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Transportation, Warehousing & Utilities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EUTNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Utilites", :col => "repeat:3:14" , :frequency => "M"}|,
    'ETWNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Transportation & Warehousing", :col => "repeat:3:14" , :frequency => "M"}|,
    'ETWTANS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Air Transportation", :col => "repeat:3:14" , :frequency => "M"}|,
    'EIFNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Information", :col => "repeat:3:14" , :frequency => "M"}|,
    'EIFTCNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Telecommunications", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_FIRNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Financial Activities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EFINS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Finance & Insurance", :col => "repeat:3:14" , :frequency => "M"}|,
    'ERENS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Real Estate & Rental & Leasing", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_PBSNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Professional & Business Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EPSNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Professional, Scientific & Tech. Svcs.", :col => "repeat:3:14" , :frequency => "M"}|,
    'EMANS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Management of Companies & Enterprises", :col => "repeat:3:14" , :frequency => "M"}|,
    'EADNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Management & Remediation Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EADESNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Employment Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_EDHCNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Educational & Health Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EEDNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Educational Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EED12NS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Elementary & Secondary Schools", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Health Care & Social Assistance", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCAMNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Ambulatory Health Care Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCHONS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Hospitals", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCNRNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Nursing & Residenial Care Facilities", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCSONS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Social Assistance", :col => "repeat:3:14" , :frequency => "M"}|,
    'EHCSOIFNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Individual & Family Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'E_LHNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Leisure and Hospitality", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAENS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Arts, Entertainment, & Recreation", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Accommodation & Food Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFACNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Accommodation", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFFDNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Food Services & Drinking Places", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAFFDRSNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Full-Service Restaurants", :col => "repeat:3:14" , :frequency => "M"}|,
    'EOSNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Other Services", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVFDNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Federal Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVFDDDNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Department of Defense", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVFDSPNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Naval Shipyard", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVSTNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:State Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVSTEDNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:State Education", :col => "repeat:3:14" , :frequency => "M"}|,
    'EGVLCNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:Local Government", :col => "repeat:3:14" , :frequency => "M"}|,
    'EAGNS@MAU.M' => %Q|Series.load_from_download "%Y@hiwi.org", { :file_type => "xls", :start_date => "1990-01-01", :sheet => "MCty", :row => "header:col:1:AGRICULTURE", :col => "repeat:3:14" , :frequency => "M"}|
    
  }
  
  # hiwi_upd_hon = {
  #   
  # }
  # 
  # hiwi_upd_haw = {
  #   
  # }
  # 
  # hiwi_upd_mau = {
  #   
  # }
  # 
  # hiwi_upd_kau = {
  #   
  # }
  
  
  p = Packager.new
  p.add_definitions hiwi_upd
  p.write_definitions_to "/Volumes/UHEROwork/data/bls/update/hiwi_upd_NEW.xls"
end

# 
# 
# 'E_NFNS' => 'WAGE & SALARY JOBS',
# 'E_PRNS' => 'Total Private',
# 'E_GDSPRNS' => 'Goods-Producing',
# 'ECTNS' => 'Nat. Resources & Mining & Construction',
# 'ECTBLNS' => 'Construction of Buildings',
# 'ECTSPNS' => 'Special Trade Contractors',
# 'EMNNS' => 'Manufacturing',
# 'EMNDRNS' => 'Durable Goods',
# 'EMNNDNS' => 'Non-Durable Goods',
# 'E_SVCPRNS' => 'Service-Providing',
# 'E_PRSVCPRNS' => 'Private Service-Providing',
# 'E_TTUNS' => 'Trade, Transportation & Utilities',
# 'EWTNS' => 'Wholesale Trade',
# 'ERTNS' => 'Retail Trade',
# 'ERTFDNS' => 'Food & Beverage Stores',
# 'ERTFDGSNS' => 'Grocery Stores',
# 'ERTCLNS' => 'Clothing & Clothing Accessories Stores',
# 'ERTGMNS' => 'General Merchandise',
# 'ERTGMDSNS' => 'Department Stores',
# 'E_TUNS' => 'Transportation, Warehousing & Utilities',
# 'EUTNS' => 'Utilites',
# 'ETWNS' => 'Transportation & Warehousing',
# 'ETWTANS' => 'Air Transportation',
# 'EIFNS' => 'Information',
# 'EIFTCNS' => 'Telecommunications',
# 'E_FIRNS' => 'Financial Activities',
# 'EFINS' => 'Finance & Insurance',
# 'ERENS' => 'Real Estate & Rental & Leasing',
# 'E_PBSNS' => 'Professional & Business Services',
# 'EPSNS' => 'Professional, Scientific & Tech. Svcs.',
# 'EMANS' => 'Management of Companies & Enterprises',
# 'EADNS' => 'Management & Remediation Services',
# 'EADESNS' => 'Employment Services',
# 'E_EDHCNS' => 'Educational & Health Services',
# 'EEDNS' => 'Educational Services',
# 'EED12NS' => 'Elementary & Secondary Schools',
# 'EHCNS' => 'Health Care & Social Assistance',
# 'EHCAMNS' => 'Ambulatory Health Care Services',
# 'EHCHONS' => 'Hospitals',
# 'EHCNRNS' => 'Nursing & Residenial Care Facilities',
# 'EHCSONS' => 'Social Assistance',
# 'EHCSOIFNS' => 'Individual & Family Services',
# 'E_LHNS' => 'Leisure and Hospitality',
# 'EAENS' => 'Arts, Entertainment, & Recreation',
# 'EAFNS' => 'Accommodation & Food Services',
# 'EAFACNS' => 'Accommodation',
# 'EAFFDNS' => 'Food Services & Drinking Places',
# 'EAFFDRSNS' => 'Full-Service Restaurants',
# 'EOSNS' => 'Other Services',
# 'EGVNS' => 'Government',
# 'EGVFDNS' => 'Federal Government',
# 'EGVFDDDNS' => 'Department of Defense',
# 'EGVFDSPNS' => 'Naval Shipyard',
# 'EGVSTNS' => 'State Government',
# 'EGVSTEDNS' => 'State Education',
# 'EGVLCNS' => 'Local Government',
# 'EAGNS' => 'AGRICULTURE',
# 


# 
#   
#  #   sox.add "PICTSGFNS@US.M",       Series.load_pattern("1964-01-01", "M", pathPICT, "fixed", "block:9:1:12", "repeat_with_step:7:29:2")
#     sox.write_xls
#     NotificationMailer.deliver_new_download_notification "Monthly HIWI Employment (rake HIWI_upd_m)", sox.output_summary
#   end
# end
