require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DataListsController do

  # This should return the minimal set of attributes required to create a valid
  # DataList. As you add validations to DataList, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all data_lists as @data_lists" do
      data_list = DataList.create! valid_attributes
      get :index
      assigns(:data_lists).should eq([data_list])
    end
  end

  describe "GET show" do
    it "assigns the requested data_list as @data_list" do
      data_list = DataList.create! valid_attributes
      get :show, :id => data_list.id.to_s
      assigns(:data_list).should eq(data_list)
    end
  end

  describe "GET new" do
    it "assigns a new data_list as @data_list" do
      get :new
      assigns(:data_list).should be_a_new(DataList)
    end
  end

  describe "GET edit" do
    it "assigns the requested data_list as @data_list" do
      data_list = DataList.create! valid_attributes
      get :edit, :id => data_list.id.to_s
      assigns(:data_list).should eq(data_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DataList" do
        expect {
          post :create, :data_list => valid_attributes
        }.to change(DataList, :count).by(1)
      end

      it "assigns a newly created data_list as @data_list" do
        post :create, :data_list => valid_attributes
        assigns(:data_list).should be_a(DataList)
        assigns(:data_list).should be_persisted
      end

      it "redirects to the created data_list" do
        post :create, :data_list => valid_attributes
        response.should redirect_to(DataList.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved data_list as @data_list" do
        # Trigger the behavior that occurs when invalid params are submitted
        DataList.any_instance.stub(:save).and_return(false)
        post :create, :data_list => {}
        assigns(:data_list).should be_a_new(DataList)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DataList.any_instance.stub(:save).and_return(false)
        post :create, :data_list => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested data_list" do
        data_list = DataList.create! valid_attributes
        # Assuming there are no other data_lists in the database, this
        # specifies that the DataList created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DataList.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => data_list.id, :data_list => {'these' => 'params'}
      end

      it "assigns the requested data_list as @data_list" do
        data_list = DataList.create! valid_attributes
        put :update, :id => data_list.id, :data_list => valid_attributes
        assigns(:data_list).should eq(data_list)
      end

      it "redirects to the data_list" do
        data_list = DataList.create! valid_attributes
        put :update, :id => data_list.id, :data_list => valid_attributes
        response.should redirect_to(data_list)
      end
    end

    describe "with invalid params" do
      it "assigns the data_list as @data_list" do
        data_list = DataList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DataList.any_instance.stub(:save).and_return(false)
        put :update, :id => data_list.id.to_s, :data_list => {}
        assigns(:data_list).should eq(data_list)
      end

      it "re-renders the 'edit' template" do
        data_list = DataList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DataList.any_instance.stub(:save).and_return(false)
        put :update, :id => data_list.id.to_s, :data_list => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested data_list" do
      data_list = DataList.create! valid_attributes
      expect {
        delete :destroy, :id => data_list.id.to_s
      }.to change(DataList, :count).by(-1)
    end

    it "redirects to the data_lists list" do
      data_list = DataList.create! valid_attributes
      delete :destroy, :id => data_list.id.to_s
      response.should redirect_to(data_lists_url)
    end
  end

end
